### ISSUE TITLE
Keyboard hook

### ISSUE THREAD

**Issue by d-bug** [kimmknight/remoteapptool#126]
keyboard language change (Shift+Alt) does not work

Client: Windows 10 Pro and Windows 11 Home
Server: Windows Server 2022 Datacenter (Azure based VM)

I have tried all methods 0,1,2 with no success?

Any suggestions will be welcome

Thank you

**Comment by MrBrianGale** [comment]
As a guess - do you have that hotkey configured on the SERVER?
There is no way to add what you requested to the remoteapptool as that's not what's running when you are doing stuff with the remote app. RemoteAppTool is just a frontend and configuration tool for RemoteApps which is a part of the RDP protocol. The problem MAY be that the server isn't configured to capture those hotkeys OR it could be your RDP application doesn't properly capture "shift+alt".
ALL remote apps run on the SERVER, so anything configured and set up locally is not being captured. If, for example, you set the date on the server to be 2025 instead of 2024, all applications run from the remote app will see the date as 2025 even though your local machine is set to 2024.
