### ISSUE TITLE
Alt+Tab after the connection is stuck and cannot be operated, but the program is not stuck and does not lose focus

### ISSUE THREAD

**Issue by GoblinCwl** [kimmknight/remoteapptool#129]
Alt+Tab after the connection is stuck and cannot be operated, but the program is not stuck and does not lose focus

host: Windows11 23h2
remote: Windows11 LTSC 24h2

**Comment by MrBrianGale** [comment]
This isn't a problem with remoteapptool or with remoteapps in general. This is by design.
When the remoteapp is in focus, keyboard controls are happening server side, not client side. So alt+tab is being sent to the server. Since there is no alternate window to switch to, nothing happens.

If I misunderstood your bug, my below answer and first sentence are still valid - this is not a bug with RemoteAppTool or RemoteApps, it is a bug/feature request with the client side tool.

The behavior you are seeing is the behavior of your RDP app, not remoteapptool. If you are seeing issues with the client tool (RDP tool, probably mstsc, but could be any number of tools that exist), and you need or expect different behavior, you should reach out to the RDP tool creator (Microsoft if you are using mstsc for example) and request a change in behavior.

**Comment by GoblinCwl** [comment]
After my repeated research, I found that this problem only exists in Windows 11 24h2 version, I hope it can help people who encounter the same problem
