### ISSUE TITLE
Can't create icons without error messages

### ISSUE THREAD

**Issue by sashaqwert** [kimmknight/remoteapptool#18]
Today I decided to create icons for RemoteApps, but only one icon and an RDP file were created, then an error message popped up.
I enclose the original message in Russian and its translation into English:

[russian.txt](https://github.com/kimmknight/remoteapptool/files/4803142/russian.txt)
[English (Google translate).txt](https://github.com/kimmknight/remoteapptool/files/4803185/English.Google.translate.txt)

I create an RDP file and icons with the following settings:

![изображение](https://user-images.githubusercontent.com/24974508/85112220-f73d3200-b21d-11ea-9ff4-a898a69fe6c9.png)

RemoteApp Tool works through RDP (regular session, not RemoteApp).

RemoteApp Tool version: 5.3.0.0 (installed by latest installer)
Windows 10 pro 1909 x64 10.0.18363.900
Intel core i7-7820X 3,6 GHz
RAM: 32 GB

**Comment by MrBrianGale** [comment]
Can I get you to try this version:
https://github.com/MrBrianGale/remoteapptool/releases/tag/AdvancedOptions_RDPOnly

I am not sure if it'll fix things, but the bug may be corrected in that version.
If the bug exists in that version as well,, I can dig through the code and figure out a fix.

Just to confirm the steps you took to create that bug, you do the normal steps to make the app in the main window then click on Create client connection, leave everything at default except click on "create icon files" and then click on Create, correct?
Do you get the same error when creating icons for a simple program (such as NotePad) as with a more complex one (such as MindManager 2020 from your screenshot)?
The error message is helpful, but I am not certain what is causing it at this time and it maybe fixed in my release through an accidental bug fix (fixed a bug without even knowing about it).

**Comment by MrBrianGale** [comment]
EDIT - just tested this and I agree the bug exists.  Debugging it now and will have a release based on the 5.4.0.0 build.
No ETA at this time, as I am uncertain what the actual bug is, but shouldn't be too complicated of a bug.

**Comment by MrBrianGale** [comment]
Fixed this faster than I expected.  Found the bug and the fix is ready for testing:
https://github.com/MrBrianGale/remoteapptool/releases/tag/CreateIcon

Can I get you to give that version a shot?  if it works well, I will create a pull request for it.  My testing indicates this should fix the bug, but would like another set of eyes on it.

**Comment by sashaqwert** [comment]
OK.  I will try to test this version tomorrow.

**Comment by MrBrianGale** [comment]
I am 95% confident that the bug should be fixed with the changes I did, but just want to be sure before making a pull request.

Thanks for testing it!

**Comment by sashaqwert** [comment]
> 
> 
> Fixed this faster than I expected. Found the bug and the fix is ready for testing:
> https://github.com/MrBrianGale/remoteapptool/releases/tag/CreateIcon
> 
> Can I get you to give that version a shot? if it works well, I will create a pull request for it. My testing indicates this should fix the bug, but would like another set of eyes on it.

I tested this version. No error messages.

**Comment by kimmknight** [comment]
Merged the fix, nice work sashaqwert and MrBrianGale
