### ISSUE TITLE
Add rdpsign.exe integration

### ISSUE THREAD

**Issue by kimmknight** [kimmknight/remoteapptool#4]
https://technet.microsoft.com/en-us/library/cc753982(v=ws.11).aspx

https://github.com/nfedera/rdpsign

http://www.thinstuff.com/faq/index.php?action=artikel&id=112

**Comment by bmg002** [comment]
I think I have this working.  I have tested it in Windows 10 and Windows Server 2008 R2 and in both cases I was able to pick a certificate file and generate a signed RDP file.
I will be making the pull request for this right away.

**Comment by kimmknight** [comment]
Wow, good stuff! I'll do some testing within the next 2-3 days and merge if all good!

**Comment by bmg002** [comment]
No problem.  I say take your time going over the code and testing it.  I would rather not be responsible for breaking your application.
One fun thing about that rdpsign application, there are different arguments depending on your rdpsign.exe version.  I did some testing and Windows Server 2008 R2 uses /sha1 while Windows 10 needs /sha256 for the argument.  So I looked at the file version on Windows 10 and Windows Server 2008 R2 and made a guess that anything prior to Windows 10's rdpsign version would need /sha1 and windows 10 and later would need /sha256.  Unfortunately, I do not have a copy of all different windows versions to test it on.  It's too bad MS can't just provide a single argument of "sha" or "hash" or something so you don't need to do the trial and error approach.
If my approach doesn't work though (too many times detecting the wrong rdpsign version for example) I can investigate implementing the rdpsign tool inside the dll instead of calling out to it.

**Comment by kimmknight** [comment]
That's interesting (although not unexpected) that they changed the parameter format between versions. They have done the same with shutdown.exe - when entering the number of seconds before shutdown, some versions require two digits minimum, other versions only require one. Annoying!

Given that difference, I will take your advice and spend some extra time testing on different Windows/Server editions.

**Comment by bmg002** [comment]
I am also not positive I followed your coding standards or not.  I kind of just went wild with it in a 2 day, sprint.  If things are named poorly or not as per your standards, let me know and I can fine tune it.

**Comment by kimmknight** [comment]
I am honoured that you think I have standards :-)

**Comment by kimmknight** [comment]
Absolutely love your work on this. You've made a great addition of functionality to the tool!

I've tweaked your changes (and the UI) a bit - let me know what you think.

I'm not sure if i've done it the correct way, but I've pushed my changes back to [bmg002:Issue4]

**Comment by bmg002** [comment]
Was reviewing code and I like what you did.  My first "huh?" moment was why the RDPSign.vb file got the System.Windows.Forms, but that was needed for the messagebox.

My habit is to have DLL's not bring up any popup boxes as then you can use the DLL in a console app, android app, iOS app, whatever, but I see the benefit of using it here.  In theory, we should never hit that line of code that needs the messagebox as you are doing a check to see if rdpsign exists before you do much else with signing RDP files, but never hurts to have the extra check.

I think the changes are good if you are wanting to merge them into yours?

**Comment by bmg002** [comment]
Also, what you did I think was right.  Pushing the changes back to mine I mean.  I am not 100% familiar with Github either, so I am learning a bit of this as well.
Something I need to figure out is how to get your master pulled over top of my master, but I think I know how to do that.  Worst case, I blow up my master branch and need to re-fork it, but the other branches will be fine.

**Comment by bmg002** [comment]
Rebased the Issue4 branch off of your master to reduce the potential for a merge conflict.
Pull request SHOULD now be your master + the changes that we did to fix this issue.

If you are happy with it, this is another pull that can be done and an issue closed!  3 issues left!

**Comment by kimmknight** [comment]
It's great to hear a more experienced developers thoughts/habits on where checks/error messages should go - thanks! On one hand, an extra check seems sensible, on the other, I've added (probably unnecessary) complexity and dependency to your library.

**Comment by kimmknight** [comment]
Merged!
