### ISSUE TITLE
Matlab dependencies not found

### ISSUE THREAD

**Issue by Codimon159** [kimmknight/remoteapptool#54]
Hello,
im trying to run a compiled matlab app with the remote app tool which needs a matlab runtime. I installed the runtime on the host and the client but there is an error saying runtime not found. 

Any tips?

Thanks

**Comment by MrBrianGale** [comment]
My first step would be to try running the app on the remote server and bake sure it runs. If it doesn't run, it won't run as a remote app either.

**Comment by Codimon159** [comment]
Thanky for your reply!
The program is running fine on both systems.

**Comment by MrBrianGale** [comment]
My guess (without having access to your system) is that it is related to how Windows is running the application on the server side.  The nice thing about RemoteApps is you don't need to install ANYTHING on the local machine (unless it is Linux based, then you will need to make sure you put an RDP client on there).  You can even use remoteapps from an iphone or android device, so installing the runtime on the client is not required.

Essentially, RemoteApps are running the application ON the server side but sending the graphical output of the application on the client side.

What I would try is in your application, when you go to compile it, make sure the references to the MatLab DLL's are set to "copy local".  What I am expecting is happening is that there is some chaining is happening incorrectly in the application possibly due to the RemoteApp not being a full login.  Or another possibility - are the DLL's in use by your custom tool stored on a network drive?  If so, are you using the UNC path or the drive letter?  Drive letter will not work unless your application is mapping the drive on the server.

Alternately, this MAY be a limitation of MatLab.  One other thing you could try is to have everyone log out of the server to ensure no users are using your tool or MatLab or causing any locking on any of the DLL's or anything on the system.  Then try running the application via RemoteApp.  It MAY be that MatLab doesn't like seeing multiple people logged in, or MatLab may have some restrictions on how it's DLL's are allowed to be used and RemoteApps is not a valid method of using them.
I've seen tools designed before that work fine on a desktop and work fine if 1 user uses it on a server, but as soon as multiple people start using the tool on the server, things start to break.

What I would check is:
1 - are you using any "Drive letter" paths in your application?  If so, are any of these network drives?  If so, you will need to change the path to a UNC path rather than a drive letter.
2 - if drive letter paths are not the problem, I would change all application references for DLL's that are not "MICROSOFT" related to "copy local".  Even the microsoft ones should be safe to set copy local, but may cause security issues or incompatibilities when you start changing OS's (server 2019 vs 10 for example).
3 - the error about the runtime not found, are you certain it is the MatLab runtime that is missing?

If the above doesn't help, could you post a screenshot of the error and (if possible without violating any NDA or anything) a copy of the tool you are trying to use with remoteapps along with installation instructions and steps to reproduce the error (does it happen on application load OR does it happen only after you click a few things)?
Not sure when I'll have time to dig deeper into your specific issue, but having those sorts of things will help me (and others) dig into it.

**Comment by Codimon159** [comment]
Thank you very much for your reply!
I will check those points.
If you want to investigate the issue i can provide you with a helloworld matlab demo program (very slow) producing the error message and a screenshot of the error message:

![grafik](https://user-images.githubusercontent.com/47380828/112489227-89aacd00-8d7e-11eb-93b1-9c74c5243b46.png)

[Program_Test.zip](https://github.com/kimmknight/remoteapptool/files/6205409/Program_Test.zip)

Matlab Runtime used for the software:
https://ssd.mathworks.com/supportfiles/downloads/R2020a/Release/6/deployment_files/installer/complete/win64/MATLAB_Runtime_R2020a_Update_6_win64.zip

**Comment by MrBrianGale** [comment]
Yikes that is a big download... 2.5 GB download.
To confirm before I let that download run for a few hours, the resulting ZIP file contains the file "mclmcrrt9_8.dll", correct?

**Comment by kimmknight** [comment]
No update. Will close. Reopen if there are any updates
