### ISSUE TITLE
two seamless app from same computer cannot work together

### ISSUE THREAD

**Issue by ericxin1982** [kimmknight/remoteapptool#55]
Hi there,

I encountered an issue is I did two seamless rdp icon from the same pc, but I found I cannot run them at the same time, is it a bug or how I can solve this?

Thanks
Eric

**Comment by MrBrianGale** [comment]
I am not sure what you mean by "seamless" apps, but this sounds like a protocol limitation and not a limitation of the tool.
That being said, I know I have run 2 applications at the same time without any problems.  Are you connecting to a Windows Server OS or a Windows Desktop OS?  With Server I know I have run Excel and other programs at the same time with no issues.

**Comment by ericxin1982** [comment]
![image](https://user-images.githubusercontent.com/9047436/113378860-a3fe2f80-93aa-11eb-9eeb-8f5f378913d6.png)
These two seamless rdp files I generated by remoteapptool, this rdp computer is windows 10 Pro.
I ran 1App.rdp, and I ran 2App.rdp, then the 1App would be disconnected.
So you meant, I can work more than 1 seamless rdp application through windows Server OS without problem right?

**Comment by kimmknight** [comment]
I've encountered this before. The second connection tries to use a new RDP session. There are a few possible causes (not related to RemoteApp Tool). Last time I had this issue it was because the server address was different in each RDP file: One used the hostname, one used the IP address. Definitely check this first.

As i don't believe this issue is related to RemoteApp Tool, I will close this issue.

If you'd like to explore this further, try posting in the google group:

https://groups.google.com/g/remoteapptool?pli=1

**Comment by ericxin1982** [comment]
ok, thanks
