### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by gaozw1** [kimmknight/remoteapptool#57]
when I double-click the .rdp file in the Microsoft Remote Desktop for Mac ,it had a problem
```
We couldn't connect to the remote PC because the PC can't be found. Please provide the fully-qualified name or the IP address of the remote PC, and then try again.

Error code: 0x104
```

I search this problem with Internet and I found [three ways](https://appuals.com/how-to-fix-remote-desktop-error-code-0x104/),however no way did work!
I don't know how to solve the problem. I can connect windows, but cannot connect remoteapp
client:
macOS 10.15.7

host:
windows10 Pro、windows10 enterprise

**Comment by MrBrianGale** [comment]
I think that the error message is telling you exactly what is wrong - it cannot find the PC.
Are you able to use Microsoft Remote Desktop for Mac to connect to the Windows 10 machines without using the remoteapptool generated RDP file?  I highly suspect that you cannot.
If you can, the problem is VERY likely to be a misconfigured rdp file. Open the .rdp file in the equivalent to notepad and edit the machine name to match whatever you entered in the Microsoft Remote Desktop for Mac tool.

If you cannot, fixing your network related issues is beyond the scope of this git project.  That is something you will need to figure out on your own or with your network team.  Chances are it is related to firewall or VLAN configuration (if this is an enterprise machine) or potentially even VPN.

**Comment by MrBrianGale** [comment]
Were you able to modify the RDP file and get connected?

**Comment by zhtengw** [comment]
I just encountered the same issue and managed to resolve it. The root cause might be different in my case, but I’d like to share my solution for anyone who comes across this issue in the future.

Here’s what happened in my scenario:
While using the Windows App on macOS, I was able to connect via Remote Desktop Connection, but when using the .rdp file generated by the tool, I got Error code: 0x104.
It was clearly not a network issue, since both the Remote Desktop Connection and the remote app connection were using the same IP and port.
I then tested with another Windows 11 client and found that the generated .rdp file worked fine there.

After inspecting the .rdp file in a text editor and testing different settings one by one, I identified that the issue was related to the `alternate full address:s:` field.
Initially, I thought this setting was just a display alias, but after testing, I realized it actually takes higher priority than `full address:s:`.
By either setting the `alternate full address:s:` value to the same IP as in `full address:s:`, or simply removing the `alternate full address:s:` line entirely, I was able to connect to the remote app successfully from macOS.

Hope this helps anyone facing a similar situation!
