### ISSUE TITLE
remote app black border

### ISSUE THREAD

**Issue by wangzhengzhen** [kimmknight/remoteapptool#58]
![image](https://user-images.githubusercontent.com/6226945/130740123-a131ce66-4169-411b-ad5e-d5e761306944.png)

**Comment by MrBrianGale** [comment]
The black border is due to the RDP client, not due to Remote App.
For example, the MAC tool has a bug that caused that black boarder on some apps as can be seen here:
https://social.technet.microsoft.com/Forums/windowsserver/en-US/e0d67f7b-10a3-4d72-9e01-c6e10668361c/office-2016-has-a-black-border-surrounding-it-in-published-apps

Quick google brings up a LOT of results for this issue.

I am closing this issue as it is not a problem with the remote app tool, but with your RDP client.  You should open a support case with the creator of that RDP client.
