### ISSUE TITLE
Does not prevent user from opening complete desktop RDP connection using the same credentials

### ISSUE THREAD

**Issue by ReckonCiler** [kimmknight/remoteapptool#62]
This works great, but unfortunately I found that if the user does not open the rdp file but instead simply attempts to connect directly to the remote PC's desktop that also works. I tried several ways of preventing this, including a track to have 'logoff.exe' run on startup in the local policies but that does not seem to work with Windows 10 Pro.

Is there some other way to restrict the user to only run the one application offered through the .rdp file? I've been Googling and trying for more than one day and nothing seems to actually work, even things that are supposed to.

**Comment by pgferrero** [comment]
My solution running an Access app has been to run the app in the Access Runtime version, also having the startup program for all users in the GPO be the Access Runtime.  If a user tries to connect to the desktop instead of running the app via the rdp file they are funneled into running Access Runtime, and without a database to open it simply opens Access, tells them that they can't open Access in Runtime, and dumps them off the server.

**Comment by MrBrianGale** [comment]
This tool isn't designed to prevent RDP access.  It actually requires RDP access or the remoteapp won't start as remoteapp is part of the RDP protocol.
This tool isn't designed to reinvent the wheel of RemoteApps, it is designed to bring RemoteApps to non-Server environments as well as to ease the setup of RemoteApps on a Server environment.  It leverages the Microsoft RemoteApp framework already in place as can be seen by the fact that the tool generates a standard RDP file in the end.  What isn't as apparent is the back-end work on the server side that is used to configure the remoteapp to work.  BUT the back-end stuff is still just configuration on the server side and utilizing the built-in RemoteApp framework that exists in the RDP protocols.
