### ISSUE TITLE
[feature]make every user app session running in seperate container

### ISSUE THREAD

**Issue by wonleing** [kimmknight/remoteapptool#66]
Do we have a plan on making every user app backend session running in seperate container?
This can make every session safe, avoid file or resource conflict, avoid the whole service or system corrupt.

**Comment by MrBrianGale** [comment]
I am not sure what you mean by "in a seperate container".  Each remote desktop app would run in its own user session which is handled by the OS, but beyond that, it would need to be set up on the server side or application side to ensure that it is running in a container if you need it running in a container.
This tool is just to allow for remote apps to be used without needing the overhead of the windows server approach.

**Comment by wonleing** [comment]
one remoteapptool server can support N users,  each user's connection suppose running in a seperate process inside remoteapptool  service. When some user did hack or file/resource confliction, the whole service could be corrupted.
I want to keep each user's process in a seperate docker container, instead of put the whole remoteapptool service into a container. This supposes to consume less CPU and memory

**Comment by MrBrianGale** [comment]
That is something that would be outside the scope of this project for sure for many reasons, but one of them being that docker is not pre-installed on any computers and requires some pre-configuration to set up.
If you are needing things to run inside a docker container, which I am not certain you are correct on consuming less CPU and memory, I would actually expect it to consume more as you have the overhead of docker running along with your application, you would need to have that as your startup process.  What I mean is you would need a script of some sort to start the docker instance and your user application rather than starting the application itself.  This will increase application startup time as well.
My opinion, this is a lot of overhead with little benefit.
While I do agree that if there is a file or resource conflict you could run into problems, a properly written service would NOT corrupt.  If the application is designed to be run on a server, it would be designed to handle multiple users running the application at the same time.  In the event multiple users tried to write to a shared file/resource, Windows handles that already at the filesystem level to prevent corruption from happening.  The worst case scenario with it is that the first user to save would lose their work as the second save would overwrite the first save.

But, like I said, having a separate docker container is entirely possible without making changes to remoteapptool by having a script run for the remote app rather than the application itself.  The main intent of this tool is to make setting up and using remote apps an easier process with less overhead than the windows server process.  By adding in docker, it is extra overhead, extra initial setup, extra maintenance (need to make sure docker gets updated AND that docker updates don't break remoteapptool), for little benefit.
