### ISSUE TITLE
Warn if unsupported edition of Windows detected

### ISSUE THREAD

**Issue by kimmknight** [kimmknight/remoteapptool#7]

**Comment by bmg002** [comment]
I was thinking about this enhancement and debating on how to implement it.
My understanding is that you need a Desktop version of windows at XP SP3 or newer and the edition needs to be professional or higher.  Doing a simple string comparison on it would be the easiest way to implement this for an English implementation of the feature, but I am not 100% sure how you make that work across multiple languages.
On a server side it is easy as all versions of Windows server above 2008 seem to support this from what I could tell.
On top of that, there could be problems if Microsoft decides to change something.  What happens if Microsoft decides that with Windows 11, RemoteApps will work in Home edition?  Or the opposite and it ONLY works in Enterprise edition?  Or they completely rename things so instead of "home" and "pro", they call it "personal" and "business"?
Plus, how do we maintain the list?  Does a new version of the Remote App Tool need to be released for each new windows version that gets pushed out just to maintain the list?
If Microsoft (or some other 3rd party) published a website that was well maintained as to which versions of Windows supported RemoteApps, this would be a trivial thing to implement.  I was not able to find one that was well maintained though.  Most of the ones I found were only up to date for Windows 7 or 8 or 8.1.  And the one that I found that was up to date for Windows 10, it was a blog and would require some special parsing of the paragraphs to find the correct information.

My thoughts on implementing this if you think it is a good idea (and I can help implement it) would be to scan the registry to determine if it is a Server edition of windows in which case it will work or if it is a "Home" edition of windows in which case it won't work and give a warning on start about the Home edition with a checkbox to ignore the warning as it MAY work on a future windows home edition.

Thoughts?

**Comment by kimmknight** [comment]
You've raised a good point about multiple languages. Also about how to keep the app/list up-to-date.

My original thoughts were that we need to determine 2 things - the version and the edition.

IF a known working version/edition is detected: No message
IF a known not-working version/edition is detected: Warn, but allow the user to continue
IF an unknown version/edition is detected: Notify the user that it may or may not work and allow them to continue

That said, I think given the potential complexity of multiple languages and dependency on an accurate, up-to-date list of compatible OSes adds an unnecessary amount of work (and potential dependency on a hosted online compatibility list, making the app less "self-contained"). Instead, I think users could just rely on the information provided when they download the app. If you agree, I'll close off the issue...?

**Comment by bmg002** [comment]
I agree and I am thinking we could put a thing in the readme indicating that it may or may not work on specific versions of windows such as Home, but that it should work on all versions of windows server from 2008 onwards.
And then this issue should be good to close?

**Comment by kimmknight** [comment]
Cool, yep for the moment, I'm happy to leave a note in the readme and keep linking to the compatibility list in the wiki
