### ISSUE TITLE
Add Windows Store Apps

### ISSUE THREAD

**Issue by kylejericson** [kimmknight/remoteapptool#80]
Is there a way to add MS Store apps like Minecraft for example?

**Comment by MrBrianGale** [comment]
Ms store apps should work with this no problem. Games on the other hand are mostly not going to work. This is because the RDP protocol doesn't use the GPU in the same way.
Any executable (ie any program) should work with this but the RDP protocol may limit which ones work correctly.

Coding issue as this isn't a problem with the tool (remoteapptool) but a problem with the protocol (RDP).
